-- -- endpoint.nvim 插件配置：提供跨框架 API 端点模糊搜索
-- return {
--   {
--     "zerochae/endpoint.nvim",
--     dependencies = {
--       "nvim-telescope/telescope.nvim",
--     },
--     -- 只在 Java 和相关文件类型中加载，针对 Spring Boot 项目优化
--     ft = { "java", "kotlin", "groovy", "xml", "yaml", "yml", "properties" },
--     cmd = { "Endpoint", "EndpointRefresh" },
--     keys = {
--       {
--         "gl",
--         function()
--           require("endpoint").find({})
--         end,
--         desc = "Endpoint: search",
--         -- 只在相关文件类型中启用快捷键
--         ft = { "java", "kotlin", "groovy", "xml", "yaml", "yml", "properties" },
--       },
--     },
--     -- 添加条件加载：检测是否为 Spring Boot 项目
--     cond = function()
--       local cwd = vim.fn.getcwd()
--       -- 检查是否存在 Spring Boot 相关文件
--       return vim.fn.filereadable(cwd .. "/pom.xml") == 1 
--         or vim.fn.filereadable(cwd .. "/build.gradle") == 1
--         or vim.fn.filereadable(cwd .. "/build.gradle.kts") == 1
--         or vim.fn.isdirectory(cwd .. "/src/main/java") == 1
--     end,
--     config = function()
--       require("endpoint").setup({
--         picker = {
--           type = "telescope",
--         },
--         cache = {
--           mode = "session",
--         },
--         -- Spring Boot 项目优化配置
--         endpoints = {
--           java = {
--             extensions = { "java", "kt" },
--             patterns = {
--               -- Spring Boot 注解模式
--               "@RequestMapping",
--               "@GetMapping",
--               "@PostMapping",
--               "@PutMapping",
--               "@DeleteMapping",
--               "@PatchMapping",
--             },
--           },
--         },
--       })
--     end,
--   },
-- }

-- 返回空表，避免 LazyVim 报错
return {}